### ISSUE TITLE
Crashes when trying to use cog-vqa

### ISSUE THREAD

**Issue by Vicullum** [jiayev/GPT4V-Image-Captioner#22]
I downloaded and installed the cog-vqa and cog-chat and it seems to load fine, but after hitting the "Process Tags" button I get this error: 
Traceback (most recent call last):
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "E:\GPT4V-Image-Captioner\lib\Tag_Processor.py", line 205, in process_tags
    wordcloud_path = generate_wordcloud(folder_path, top)
  File "E:\GPT4V-Image-Captioner\lib\Tag_Processor.py", line 149, in generate_wordcloud
    wordcloud.generate_from_frequencies(dict(tag_counts))
  File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\wordcloud\wordcloud.py", line 410, in generate_from_frequencies
    raise ValueError("We need at least 1 word to plot a word cloud, "
ValueError: We need at least 1 word to plot a word cloud, got 0.

**Comment by SleeeepyZhou** [comment]
> File "E:\GPT4V-Image-Captioner\myenv\lib\site-packages\wordcloud\wordcloud.py", line 410, in generate_from_frequencies
raise ValueError("We need at least 1 word to plot a word cloud, "

> ValueError: We need at least 1 word to plot a word cloud, got 0.

It seems that the relevant tag file was not found. When you hit the "Process Tags" button, there should be relevant txt files in the folder.

**Comment by Vicullum** [comment]
What do you mean, I thought the whole point was to generate txt files with the tags. That's how it works with Kohya--all you need to do is give it a folder full of images. How do I do that with your program then?

**Comment by zhangdoudou** [comment]
I also meet such issue, and I solve it by first run image prosess to generate tags

**Comment by SleeeepyZhou** [comment]
> What do you mean, I thought the whole point was to generate txt files with the tags. That's how it works with Kohya--all you need to do is give it a folder full of images. How do I do that with your program then?

You can create a tag txt file through the Image Processing tab, and then enter the Process Tags tab to process the tag file.
I'm sorry for seeing and replying so late.
