### ISSUE TITLE
HTTP Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8000/v1/chat/completions

### ISSUE THREAD

**Issue by huangxin1745** [jiayev/GPT4V-Image-Captioner#4]
用vqa报错

**Comment by SleeeepyZhou** [comment]
可以给一下报错截图不。

**Comment by huangxin1745** [comment]
我又下载了chat，然后又点了一次安装，现在点切换是这个样子……
请按任意键继续. . . Running on local URL:  http://127.0.0.1:8848

To create a public link, set `share=True` in `launch()`.
Retrying...
========Use torch type as:torch.bfloat16 with device:cuda========


A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Please 'pip install apex'
Retrying...
False

===================================BUG REPORT===================================
D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\utils\import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\integrations\bitsandbytes.py", line 11, in <module>
    import bitsandbytes as bnb
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\cog_openai_api.py", line 407, in <module>
    load_mod(MODEL_PATH)
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\cog_openai_api.py", line 371, in load_mod
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\modeling_utils.py", line 3476, in from_pretrained
    from .integrations import get_keys_to_not_convert, replace_with_bnb_linear
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\utils\import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\GPT4V-Image-Captioner\GPT4V-Image-Captioner\myenv\lib\site-packages\transformers\utils\import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Retrying...
Retrying...
Retrying...

**Comment by SleeeepyZhou** [comment]
bitsandbytes没安装好，可以尝试再安装一下，如果不行我等会看看传一个bitsandbytes的包。

**Comment by huangxin1745** [comment]
重装后问题已解决，谢谢

**Comment by SleeeepyZhou** [comment]
好的🎉
