### ISSUE TITLE
使用单图caption，报错TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by CaiNiaoCYY** [jiayev/GPT4V-Image-Captioner#55]
Running on local URL:  http://0.0.0.0:8081

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/routes.py", line 732, in predict
    output = await route_utils.call_process_api(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/blocks.py", line 1924, in process_api
    inputs = await self.preprocess_data(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/blocks.py", line 1653, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/routes.py", line 732, in predict
    output = await route_utils.call_process_api(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/blocks.py", line 1924, in process_api
    inputs = await self.preprocess_data(
  File "/data/miniconda3/envs/env-3.10-comfyui/lib/python3.10/site-packages/gradio/blocks.py", line 1653, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not str

系统信息
gradio                       4.36.1
gradio_client                1.0.1

**Comment by linksluckytime** [comment]
我也有同样的问题
