### ISSUE TITLE
moondream

### ISSUE THREAD

**Issue by genevera** [jiayev/GPT4V-Image-Captioner#62]
I get the following stacktrace when trying to caption with moonbeam:

```python
INFO:     Started server process [2607508]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
API has started.
Exception in thread Thread-1 (answer_question):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/moondream.py", line 93, in answer_question
    answer = self.generate(
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/moondream.py", line 77, in generate
    output_ids = self.text_model.generate(
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 709, in forward
    hidden_states = self.transformer(
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 675, in forward
    else func(*args)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 541, in forward
    attn_outputs = self.mixer(
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 514, in forward
    attn_output_function(x, past_key_values, attention_mask)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 494, in _forward_cross_attn
    return attn_func(
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 491, in <lambda>
    else lambda fn, *args, **kwargs: fn(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/myenv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/genevera/src/GPT4V-Image-Captioner/moondream/modeling_phi.py", line 318, in forward
    padding_mask.masked_fill_(key_padding_mask, 0.0)
RuntimeError: The expanded size of the tensor (1041) must match the existing size (1042) at non-singleton dimension 1.  Target sizes: [1, 1041].  Tensor sizes: [1, 1042]


```

**Comment by SleeeepyZhou** [comment]
Does it seem like the input image is too large? The error is a dimension mismatch error in PyTorch. 🤯
You can try using a smaller image.

`RuntimeError: The expanded size of the tensor (1041) must match the existing size (1042) at non-singleton dimension 1.  Target sizes: [1, 1041].  Tensor sizes: [1, 1042]`
